CC = gcc  

all: QuantumAnnealing.o MQTS.o QTS.o 
  $(CC) QuantumAnnealing.o QTS.o MQTS.o -o test

MQTS.o: MQTS.cpp MQTS.h
  $(CC) MQTS.c -c -o MQTS.o

QTS.o: QTS.cpp QTS.h
  $(CC) QTS.c -c -o QTS.o

QuantumAnnealin.o: QuantumAnnealing.cpp
  $(CC) QuantumAnnealing.c -c -o QuantumAnnealing.o